### PR TITLE
Add --namespace feature

### PR DESCRIPTION
**Pull request by julien**
See Issue #25

### CODE REVIEW

**Review by jbalsas — CHANGES_REQUESTED** [review]
Hey @julien, the comment of the commit should read something like:

```
Adds blah blah...

Fixes #25
```

This way we can keep track of why things change.

Also, seems like some kind of autoformatter changed all the tests... or did you modify all those? Could you please check to see if you have some setting (maybe some `.editorrc`) that is changing something in the existing code?

If we were to add all those changes, it should be in a different commit making very clear that nothing other than formatting has actually changed.

**Comment by julien** [comment]
Hi @jbalsas,

Sorry, I'll add the title and commit message.

I don't see any `.editorconfig` in my local fork of the repository, but concerning the tests, those are actually new files I added to test the feature.

Anyway I will fix the title and submit a new PR.

Thanks

**Comment by ipeychev** [comment]
Yeah, on this project it looks like I didn't add an `.editorconfig` file, probably forgot. We need this:
```
root = true;

[*]
#  Ensure there's no lingering whitespace
trim_trailing_whitespace = true
# Ensure a newline at the end of each file
insert_final_newline = true

[*.js]
# Unix-style newlines
end_of_line = lf
charset = utf-8
indent_style = space
indent_size = 4
```

You may add it to the root folder and commit it (but please create another issue).

Thanks,

**Comment by julien** [comment]
Hi @ipeychev ok thanks, will do.

**Pull request closed without merging**
